version: '3.5'

services:
  postgres:
    container_name: postgres_dvdrental
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dvdrental
      PGDATA: /data/postgres
    volumes:
      - ./db:/data/postgres
      - ./dump:/data/dump
    ports:
      - 5432:5432
    networks:
      - postgres_net
  
  pgadmin:
    container_name: pgadmin_dvdrental
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: fake@mail.com
      PGADMIN_DEFAULT_PASSWORD: fake123
    volumes:
      - ./pgadmin:/root/.pgadmin
    ports:
      - 5050:80
    networks:
      - postgres_net

networks:
  postgres_net:
    driver: bridge
